openapi: 3.0.3

components:
  schemas:
    EmployeeRequestDto:
      type: object
      properties:
        name:
          type: string
        salary:
          type: string
    EmployeeResponseDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        salary:
          type: string
