#DB settings
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/employees_crud?currentSchema=public}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
